In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('/content/drive/MyDrive/student_resource/dataset/train.csv')
df.head()

,sample_id,catalog_content,image_link,price
0,33127,"Item Name: La Victoria Green Taco Sauce Mild, ...",https://m.media-amazon.com/images/I/51mo8htwTH...,4.89
1,198967,"Item Name: Salerno Cookies, The Original Butte...",https://m.media-amazon.com/images/I/71YtriIHAA...,13.12
2,261251,"Item Name: Bear Creek Hearty Soup Bowl, Creamy...",https://m.media-amazon.com/images/I/51+PFEe-w-...,1.97
3,55858,Item Name: Judee’s Blue Cheese Powder 11.25 oz...,https://m.media-amazon.com/images/I/41mu0HAToD...,30.34
4,292686,"Item Name: kedem Sherry Cooking Wine, 12.7 Oun...",https://m.media-amazon.com/images/I/41sA037+Qv...,66.49

In [4]:
df1 = df.drop(['image_link'], axis='columns')
df1.head()

   sample_id                                    catalog_content  price
0      33127  Item Name: La Victoria Green Taco Sauce Mild, ...   4.89
1     198967  Item Name: Salerno Cookies, The Original Butte...  13.12
2     261251  Item Name: Bear Creek Hearty Soup Bowl, Creamy...   1.97
3      55858  Item Name: Judee’s Blue Cheese Powder 11.25 oz...  30.34
4     292686  Item Name: kedem Sherry Cooking Wine, 12.7 Oun...  66.49

In [6]:
# shuffle the dataset
df1 = df1.sample(frac=1).reset_index(drop=True)
df1.head()

   sample_id                                    catalog_content  price
0     147947  Item Name: Bergamot Lemon Lime Decaf Black Tea...  46.04
1     274603  Item Name: Spice Hunter Sage Rubbed Dalmatian,...  14.10
2     117150  Item Name: Jelly Belly Valentine's Sparkling R...   6.49
3      10022  Item Name: Mexico Lindo Picante Negra Hot Sauc...  14.16
4      56696  Item Name: Outshine Fruit & Yogurt Smoothie Ap...  29.13

In [7]:
df1.shape

(75000, 3)

In [8]:
df2 = df1[:5000]

In [9]:
# sacing df2 as dnt_test
df2.to_csv('/content/drive/MyDrive/student_resource/dataset/dnt_test.csv', index=False)